services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./src/configs/settings.yml:/etc/searxng/settings.yml
      - ./src/configs/limiter.toml:/etc/searxng/limiter.toml

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - searxng
    volumes:
      - ./src/configs/nginx.conf:/etc/nginx/conf.d/default.conf
